### ISSUE TITLE
[PE-D][Tester D] Inconsistent visuals

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T09-3/tp#182] opened 2023-11-03 20:12 UTC
Only the help and find feature contains screenshots from the application to showcase what the correct outputs look like

![image.png](https://raw.githubusercontent.com/nicolengk/ped/main/files/31e2e564-13a7-4fa2-bd98-29207d725b82.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: nicolengk/ped#4

**Comment by cmHuang777** [comment] 2023-11-13 04:37
Duplicate of #189

**Closed by cmHuang777** 2023-11-13 04:37 UTC
Labels: documentation, duplicate, priority.Low
